version: "3.8"

services:
  db:
    container_name: autospace_db
    image: postgres:16
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_autospace:/var/lib/postgresql/data

  backend:
    container_name: autospace_backend
    build: .
    restart: always
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - db

volumes:
  db_data_autospace:
